before_install:
  # LibCouchbase
  - sudo wget -O/etc/apt/sources.list.d/couchbase.list http://packages.couchbase.com/ubuntu/couchbase-ubuntu1204.list
  - "sudo wget http://packages.couchbase.com/ubuntu/couchbase.key && sudo cat couchbase.key | sudo apt-key add -"
  - sudo apt-get update
  - sudo apt-get install libcouchbase2 libcouchbase-dev
  # Couchbase Server
  - sudo wget http://packages.couchbase.com/releases/2.0.0/couchbase-server-enterprise_x86_64_2.0.0.deb
  - sudo dpkg -i couchbase-server-enterprise_x86_64_2.0.0.deb
  - sudo service couchbase-server start
  # Setup Bucket for test
  - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=Administrator --cluster-init-password=password --cluster-init-ramsize=256
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=tests --bucket-type=couchbase --bucket-ramsize=100 --bucket-port=11211 --bucket-replica=0 -u Administrator -p password

language: node_js
node_js:
  - '0.10.30'